### ISSUE TITLE
open.sutd.dev

### ISSUE THREAD

**Issue by chaychoong** [OpenSUTD/sutd.dev#1]
**Project Info**
[Source URL](https://opensutd.github.io/)
[Link to repository URL](https://github.com/OpenSUTD/opensutd.github.io)

**DNS records needed**
CNAME
name: open.sutd.dev
value: opensutd.github.io.

**Brief description of the project**
A place for free and open knowledge sharing within and outside of the SUTD Community.

**Project owners**
@tlkh

**Comment by chaychoong** [comment]
Fulfilled by @chaychoong. [link](https://open.sutd.dev)

**Comment by joel-huang** [comment]
Ownself check ownself
