### ISSUE TITLE
compute.sutd.dev

### ISSUE THREAD

**Issue by tlkh** [OpenSUTD/sutd.dev#2]
**Project Info**
[Source URL if any](https://sutd-compute.github.io) sutd-compute.github.io
[Link to repository URL](https://github.com/sutd-compute/sutd-compute.github.io) https://github.com/sutd-compute/sutd-compute.github.io

**DNS records needed**
CNAME
name: compute.sutd.dev
value: sutd-compute.github.io

**Brief description of the project**

A one stop repository for guides on using the school's compute resources

**Project owners**
Tag project owners @tlkh

**Comment by chaychoong** [comment]
Fulfilled. [link](https://compute.sutd.dev)
